language: java
dist: trusty
jdk:
  - oraclejdk11
addons:
  sonarcloud:
    organization: "jabbarra"
cache:
  directories:
    - ~/.gradle
before_install:
  - chmod +x gradlew
  - echo $JAVA_HOME
  - java --version

script:
  - ./gradlew clean check sonarqube  -i
deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: ob-config-server
  on:
    repo: jabbarra/ob-config-server