language: java
dist: trusty
jdk:
  - oraclejdk11
addons:
  sonarcloud:
    organization: "jabbarra"
cache:
  directories:
    - ~/.gradle
before_install:
  - chmod +x gradlew
  - echo $JAVA_HOME
  - java --version

script:
  - ./gradlew clean check sonarqube  -i