language: java
dist: trusty
jdk:
  - oraclejdk14
addons:
  sonarcloud:
    organization: "jabbarra"
cache:
  directories:
    - ~/.gradle
before_install:
  - chmod +x gradlew
  - echo $JAVA_HOME
  - java --version
