server:
    port: 8888
spring:
    application:
        name: ob-config-server
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/jabbarra/repository-config.git
